replace involved argument for clock jump differences with 3 Lookup Args
TritonVM/triton-vm pull request #177
Opened 2023-02-03 15:22 UTC by jan-ferdinand

2023-02-04 19:09 UTC, aszepieniec requested changes
It looks like there are 3 separate Lookup Arguments. How about merging the servers? That shouldn't be too difficult.

The next step is to merge the clients also. I believe that's possible but will require some more engineering work.

2023-02-04 22:59 UTC, jan-ferdinand commented
> How about merging the servers? That shouldn't be too difficult.

I agree: the engineering effort is pretty low, there's no real reason to separate the arguments, and it saves a few columns.

> The next step is to merge the clients also.

I disagree: the red wedding should happen before we take a closer look at whether merging the clients is worth it.

2023-02-05 20:48 UTC, aszepieniec approved these changes
LGTM

2023-02-07 11:59 UTC, sshine approved these changes

2023-02-07 12:03 UTC, merged